import {createClient} from '@supabase/supabase-js';

export const supabase = createClient("https://rrepingbmmedonubxvgp.supabase.co",
"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJyZXBpbmdibW1lZG9udWJ4dmdwIiwicm9sZSI6ImFub24iLCJpYXQiOjE2NzE5MzkzMDMsImV4cCI6MTk4NzUxNTMwM30.shi_XkVkJykn4fdSK3xh3s4rY9tQY_Exq3w141tw91w")